version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4005:4005"  # Mapeamos el puerto 4005
    volumes:
      - ./data:/usr/src/app/data  # Volumen para persistir la base de datos
    environment:
      - NODE_ENV=production
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
